"""
Configuration module for ontology mapping.
"""

from .ontologies import ONTOLOGY_CONFIGS, ONTOLOGY_COMBINATIONS, SEARCH_STRATEGIES, BIOPORTAL_TO_OLS_MAPPING

__all__ = ['ONTOLOGY_CONFIGS', 'ONTOLOGY_COMBINATIONS', 'SEARCH_STRATEGIES', 'BIOPORTAL_TO_OLS_MAPPING']
